import type { Metadata } from "next";
import type { ReactNode } from "react";

import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { Container } from "@/components/shared/container";
import { PageWrapper } from "@/components/shared/page-wrapper";
import { APP_NAME } from "@/lib/constants";
import { SUPPORT_EMAIL } from "@/lib/site-config";

const LAST_UPDATED = "August 20, 2026";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${APP_NAME} collects, uses, stores, and protects your data.`,
};

export default function PrivacyPage() {
  return (
    <PageWrapper>
      <SiteHeader />
      <main id="main" className="flex-1">
        <Container className="mx-auto max-w-3xl py-16">
          <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>

          <div className="mt-8 flex flex-col gap-8 text-sm leading-relaxed text-muted-foreground">
            <section className="flex flex-col gap-3">
              <p>
                This policy explains what data {APP_NAME} collects, how it is used, and the choices
                you have. {APP_NAME} is a personal cross-device sync tool: the content you save is
                yours, and it exists to move that content between your own devices.
              </p>
            </section>

            <Section title="Information we collect">
              <ul className="ml-5 list-disc space-y-1">
                <li>
                  <strong className="text-foreground">Account data.</strong> Your email address, and
                  — if you sign in with Google or GitHub — the basic profile identifier those
                  providers return. We never receive your Google or GitHub password.
                </li>
                <li>
                  <strong className="text-foreground">Content you save.</strong> The text, code,
                  links, images, documents, and files you sync, plus their metadata (type, size,
                  timestamps, originating device).
                </li>
                <li>
                  <strong className="text-foreground">Technical data.</strong> Standard request logs
                  (IP address, browser type) generated by our hosting and database providers to keep
                  the service running and secure.
                </li>
              </ul>
            </Section>

            <Section title="How we use your information">
              <p>
                We use your data solely to operate {APP_NAME}: to authenticate you, sync your
                content across your signed-in devices in real time, and maintain and secure the
                service. We do not sell your data, and we do not use your synced content for
                advertising.
              </p>
            </Section>

            <Section title="Storage and security">
              <p>
                Your content is stored in a Postgres database (Supabase) and, for files, in private
                object storage. Every row and file is scoped to your account and enforced by
                database row-level security, so one account cannot read another&apos;s data. All
                traffic is encrypted in transit over TLS.
              </p>
            </Section>

            <Section title="Data retention">
              <p>
                To keep things tidy — especially on shared or work machines — items expire
                automatically a short time after they are created unless you pin or favorite them.
                Expired items are removed from the database. You can delete any item at any time, and
                deleting your account removes your associated content.
              </p>
            </Section>

            <Section title="Third-party services">
              <p>
                We rely on a small set of infrastructure providers to run {APP_NAME}: Supabase
                (database, authentication, storage), Vercel (application hosting), and — only if you
                choose to use them — Google and GitHub for sign-in. These providers process data on
                our behalf to deliver the service.
              </p>
            </Section>

            <Section title="Your rights">
              <p>
                You can access, export, or delete your content from within the app, and you can
                request deletion of your account and associated data by contacting us. Depending on
                where you live, you may have additional rights over your personal data.
              </p>
            </Section>

            <Section title="Contact">
              <p>
                Questions about this policy? Email us at{" "}
                <a
                  href={`mailto:${SUPPORT_EMAIL}`}
                  className="font-medium text-foreground underline underline-offset-4"
                >
                  {SUPPORT_EMAIL}
                </a>
                .
              </p>
            </Section>
          </div>
        </Container>
      </main>
      <SiteFooter />
    </PageWrapper>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="flex flex-col gap-3">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      {children}
    </section>
  );
}
